### ISSUE TITLE
Merge Spawn items into Akashic Tome

### ISSUE THREAD

**Issue by Xydryhn** [Xydryhn/SlayerCraft#3]
THis will prevent people from spawning in with about 8 different books and give players all the information they need at the start.

**Comment by stanhebben** [comment]
This has been performed using Custom Starter Gear.

The default Akashic Tome contains the following books:

- Actually Additions Manual
- Lexica Botania
- Materials and You - Armory Addendum
- Forester's Manual
- Industrial Foregoing's Manual
- On the Dynamics of Integration
- World Domination with OpenBlocks
- OpenComputers Manual
- RFTools Control Manual
- Materials and You
- Digital Guide
