### ISSUE TITLE
Unify Ingots and Nuggets

### ISSUE THREAD

**Issue by Xydryhn** [Xydryhn/SlayerCraft#4]
Convert all machine recipies if possible over to Using CoFH's Ingots and Nuggets. Some have a config option on which they default to, but the unification will greatly ease up player issues.

**Comment by Xydryhn** [comment]
Partially FIxed, Tinkers and Immersive Engineering have the settings changed

**Comment by stanhebben** [comment]
Remaining recipes have been fixed using CraftTweaker, let me know if anything is off or missing.
